http:
  port: 9090
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  dicoding:
    host: localhost
    paths: '/*'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  dicodingbin:
    url: 'https://restaurant-api.dicoding.dev/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      - rate-limit:
          - action:
              max: 3
              rateLimitBy: "${req.hostname}"
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  dicoding:
    apiEndpoints:
      - dicoding
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: dicodingbin
              changeOrigin: true
